### ISSUE TITLE
Doesn't work in Firefox Private browsing

### ISSUE THREAD

**Issue by peterbe** [slightlyoff/async-local-storage#6]
[This sample](http://www.peterbe.com/als/index.html) works in Chrome and Firefox but in Firefox private browsing I get InvalidStateError.

![screen shot 2013-10-31 at 9 26 27 am](https://f.cloud.github.com/assets/26739/1447551/3894752a-4249-11e3-8995-500f942fc350.png)

I tried this in Chrome's Incognito browsing mode and there it worked. 

If this is a problem with Firefox I'd be happy to file a bug for that there but is there anything we can do in this library?

**Comment by sole** [comment]
Probably it's a problem with Firefox in private mode:
https://bugzilla.mozilla.org/show_bug.cgi?id=781982

**Comment by peterbe** [comment]
Wow that was quick. So it appears to really be a Firefox problem. This lib shouldn't have to work around it.
